name: stripcall
description: "Fencing Tournament Assistance App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: "^3.8.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  supabase: ^2.10.2
  go_router: ^17.0.1
  intl: ^0.20.2
  flutter_secure_storage: ^10.0.0
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  firebase_analytics: ^12.1.0
  http: ^1.6.0
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.5.4
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  mockito: ^5.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

# Include test directory in the package
package:
  include:
    - test/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true
